### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by popey456963** [tillmannw/prowler#1]
Hello,

Being very dumb, like I seem to be at the moment, how would I run this?  I have done:

```
git clone ....
cd prowler
make
```

Except I can't find anything I can run, is there any documentation for this program?  Or examples?

**Comment by emirsosa** [comment]
Just run the .exe :)

Regards,

Emir Sosa
I'm mobile

**Comment by popey456963** [comment]
Wow, I'm really blind.

**Comment by emirsosa** [comment]
Idk man. Not sure how I was included in this mail; Instead of marking as
spam decided To reply with 'exe' lol.

Good luck.

Regards,

Emir Sosa
I'm mobile
